"""add all

Revision ID: 3f21b8ea202d
Revises: 1fd0bb3f3a2d
Create Date: 2021-06-13 17:20:58.293512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f21b8ea202d'
down_revision = '1fd0bb3f3a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('follows_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follows_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], )
    )
    op.create_table('posts',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media', sa.String(length=32), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('comments',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.pid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('likes',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.pid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], )
    )
    op.create_table('notifs',
    sa.Column('nid', sa.Integer(), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('for_uid', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['for_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.pid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.add_column('users', sa.Column('notif_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notif_count')
    op.drop_table('notifs')
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('followers')
    # ### end Alembic commands ###
